build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: coverapp:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $IMAGE_TAG --build-arg NPM_TOKEN=${NPM_TOKEN} .
    - docker push $IMAGE_TAG
